var knightSetListFull = {
	//"Set": ["Name","Trait","Job","Face","Body","Helmet","Armor","Cape","Cape rarity","Mainhand","Main enchant","Offhand","Off enchant","Pet","Shine"],
	"Angel": [89650, "","Divine","","","Angel","Aureole","Divine Outfit","","","Holy Blade","","Holy Tome","","",""],
	"Baker": [170, "","","Baker","","","Chef Hat","Baker Apron","","","Rolling Pin","","Baguette","","",""],
	"BlackSmith": [170, "","","Blacksmith","","","Shiny Bald Head","Blacksmith Apron","","","Blacksmith Hammer","","Pliers","","",""],
	"Cat": [480, "","Cat","","Cat","Black Cat","Cat Ears","","","","","","","","",""],
	"Devil": [89650, "","Satanic","","","Devil","Devil's Horns","Devil's Mutation","","","Demonic Trident","","Demonic Whip","","",""],
	"Dog": [424, "","Dog","","Good Dog","Dog","Dog Ears","","","","","","","","",""],
	"EatAll Panoply": [61968, "","Tainelaba","Donjon Farmer","","","EatAll Cap","EatAll Chestplate","","White","EatAll Hammer","","EatAll Shield","","EatAll",""],
	"Frog": [1695, "Glenn","Amphibian","Knight","Frog","Slimy Skin","Shiny Bald Head","Light Chestplate","Greenish","","Masamune","","Star Shield","","",""],
	"Joker": [367, "","","Joker","Clown","","Joker Hat","Minstrel Outfit","","","Jugglin Pin","","Tarot Cards","","",""],
	"King": [55055, "","","","","","","","","","","","","","",""],
	"Lizard": [424, "","Lizard","","Lizard","Reptilian","Lizard Horns","","","","","","","","",""],
	"Medium": [1837, "","Medium","","Medium","","Oracle Veil","Oracle Robe","","","Crystal Ball","","Tambourine","","",""],
	"Midas": [1773030, "Midas","Golden","King","","Rare Golden","Gold","Gold","","Golden","Gold Hammer","Durability V","Gold Shield","Durability V","","Gold"],
	"Momochang": [99002, "Momochang","Hermaphrodite","","Famous Snail","Turquoise","Slimy Mutation","Slimy Slug","","","USB Spear","","Joystick","","",""],
	"Night Hero": [186374, "Bruce","Dark","Knight","","","Stealth Helmet","Stealth Armor","","Black","Hook Pistol","","Stealth Boomerang","","",""],
	"Orc": [472, "","Orc","","Orc","Green","Orc Ears","","","","","","","","",""],
	"Pirate": [1525, "","","Buccaneer","Greedy","","Pirate Tricorn","Filibuster Outfit","","","Cutlass","","Flintlock Pistol","","Monkey",""],
	"Robot": [9430, "","Robot","","Robot","Robot","Robot Antennas","Robot Armor","","","Laser Gun","","Drill Hand","","",""],
	"Santa Claus": [105000, "","","","","","","","","","","","","","",""],
	"Snowman": [235, "","","","","","","","","","","","","","",""],
	"Wizard": [389, "Harry","","Armored Mage","Known Wizard","","Hat of Choice","Wizard Robe","","","Griffin Sword","","Magic Wand","","",""],
	"Wolf": [2064, "","","","","","","","","","","","","","",""],
	"Xmas Elf": [1969, "","","","","","","","","","","","","","",""],
	"Zombie": [840, "","Zombie","","Dead","Dead","Cubic hairstyle","Rotten Clothes","","","Stone Sword","","Stone Pickaxe","","Chicken",""],
	"Hippy": [234, "","","","","","","","","","","","","","",""],
	"Diver": [33163, "","","","","","","","","","","","","","",""],
	"Mermaid": [1603800, "","","","","","","","","","","","","","",""],
	"Ninja Master": ["","","","","","","","","","","","","","",""]
};