var knightPartListFull = {
KNIGHT_ARMOR_0_2: 'Barbarian',
KNIGHT_ARMOR_0_3: 'Barbarian (Bones)',
KNIGHT_ARMOR_2_0: 'Bronze',
KNIGHT_ARMOR_2_1: 'Bronze (Heavy)',
KNIGHT_ARMOR_1_0: 'Copper',
KNIGHT_ARMOR_1_1: 'Copper (Heavy)',
KNIGHT_ARMOR_3_0: 'Gold',
KNIGHT_ARMOR_3_1: 'Gold (Heavy)',
KNIGHT_ARMOR_1_2: 'Iron',
KNIGHT_ARMOR_1_3: 'Iron (Heavy)',
KNIGHT_ARMOR_0_0: 'Leather',
KNIGHT_ARMOR_3_2: 'Mithril',
KNIGHT_ARMOR_3_3: 'Mithril (Heavy)',
KNIGHT_ARMOR_4_2: 'Obsidian',
KNIGHT_ARMOR_4_3: 'Obsidian (Heavy)',
KNIGHT_ARMOR_4_0: 'Orichalcum',
KNIGHT_ARMOR_4_1: 'Orichalcum (Heavy)',
KNIGHT_ARMOR_2_2: 'Silver',
KNIGHT_ARMOR_2_3: 'Silver (Heavy)',
KNIGHT_ARMOR_0_1: 'Tanned Leather',
KNIGHT_ARMOR_SET_0_2: 'Barbarian Set',
KNIGHT_ARMOR_SET_0_3: 'Bone Barbarian Set',
KNIGHT_ARMOR_SET_2_0: 'Bronze Set',
KNIGHT_ARMOR_SET_1_0: 'Copper Set',
KNIGHT_ARMOR_SET_3_0: 'Gold Set',
KNIGHT_ARMOR_SET_2_1: 'Heavy Bronze Set',
KNIGHT_ARMOR_SET_1_1: 'Heavy Copper Set',
KNIGHT_ARMOR_SET_3_1: 'Heavy Gold Set',
KNIGHT_ARMOR_SET_1_3: 'Heavy Iron Set',
KNIGHT_ARMOR_SET_3_3: 'Heavy Mithril Set',
KNIGHT_ARMOR_SET_4_3: 'Heavy Obsidian Set',
KNIGHT_ARMOR_SET_4_1: 'Heavy Orichalcum Set',
KNIGHT_ARMOR_SET_2_3: 'Heavy Silver Set',
KNIGHT_ARMOR_SET_1_2: 'Iron Set',
KNIGHT_ARMOR_SET_0_0: 'Leather Set',
KNIGHT_ARMOR_SET_3_2: 'Mithril Set',
KNIGHT_ARMOR_SET_4_2: 'Obsidian Set',
KNIGHT_ARMOR_SET_4_0: 'Orichalcum Set',
KNIGHT_ARMOR_SET_2_2: 'Silver Set',
KNIGHT_ARMOR_SET_0_1: 'Tanned Leather Set',
KNIGHT_BODY_4_1: 'Angel',
KNIGHT_BODY_1_5: 'Apple',
KNIGHT_BODY_2_6: 'Black Cat',
KNIGHT_BODY_2_2: 'Blood',
KNIGHT_BODY_1_0: 'Blue',
KNIGHT_BODY_1_2: 'Dark Gray',
KNIGHT_BODY_2_8: 'Dead',
KNIGHT_BODY_4_2: 'Devil',
KNIGHT_BODY_3_0: 'Divine White',
KNIGHT_BODY_2_3: 'Dog',
KNIGHT_BODY_4_0: 'Exotic Lint',
KNIGHT_BODY_2_1: 'Ghost',
KNIGHT_BODY_1_4: 'Gray',
KNIGHT_BODY_1_10: 'Green',
KNIGHT_BODY_1_3: 'Lavender',
KNIGHT_BODY_1_9: 'Light Blue',
KNIGHT_BODY_1_7: 'Marine Blue',
KNIGHT_BODY_2_5: 'Mummy',
KNIGHT_BODY_0_0: 'Natural',
KNIGHT_BODY_0_1: 'Natural',
KNIGHT_BODY_0_2: 'Natural',
KNIGHT_BODY_0_3: 'Natural',
KNIGHT_BODY_0_4: 'Natural',
KNIGHT_BODY_0_5: 'Natural',
KNIGHT_BODY_0_6: 'Natural',
KNIGHT_BODY_0_7: 'Natural',
KNIGHT_BODY_0_8: 'Natural',
KNIGHT_BODY_0_9: 'Natural',
KNIGHT_BODY_0_10: 'Natural',
KNIGHT_BODY_0_11: 'Natural',
KNIGHT_BODY_0_12: 'Natural',
KNIGHT_BODY_0_13: 'Natural',
KNIGHT_BODY_0_14: 'Natural',
KNIGHT_BODY_1_6: 'Purple',
KNIGHT_BODY_3_1: 'Rare Golden',
KNIGHT_BODY_1_8: 'Red',
KNIGHT_BODY_2_0: 'Reptilian',
KNIGHT_BODY_3_3: 'Robot',
KNIGHT_BODY_3_2: 'Shadow Black',
KNIGHT_BODY_2_4: 'Sick Albino',
KNIGHT_BODY_2_7: 'Slimy Skin',
KNIGHT_BODY_2_1000: 'Snow',
KNIGHT_BODY_1_1: 'Turquoise',
KNIGHT_BODY_3_4: 'Wolf',
KNIGHT_CAPE_COLOR_0: 'Beige',
KNIGHT_CAPE_COLOR_21: 'Black',
KNIGHT_CAPE_COLOR_17: 'Blood',
KNIGHT_CAPE_COLOR_13: 'Blue',
KNIGHT_CAPE_COLOR_10: 'Brick',
KNIGHT_CAPE_COLOR_1: 'Brown',
KNIGHT_CAPE_4: 'Chic Cloak',
KNIGHT_CAPE_1: 'Cloak',
KNIGHT_CAPE_COLOR_8: 'Cream',
KNIGHT_CAPE_COLOR_19: 'Cyan',
KNIGHT_CAPE_COLOR_3: 'Dark Brown',
KNIGHT_CAPE_COLOR_22: 'Golden',
KNIGHT_CAPE_2: 'Good Cloak',
KNIGHT_CAPE_COLOR_4: 'Gray',
KNIGHT_CAPE_COLOR_14: 'Green',
KNIGHT_CAPE_COLOR_2: 'Greenish',
KNIGHT_CAPE_COLOR_9: 'Lavender',
KNIGHT_CAPE_COLOR_5: 'Leather',
KNIGHT_CAPE_COLOR_6: 'Light Blue',
KNIGHT_CAPE_COLOR_7: 'Light Green',
KNIGHT_CAPE_3: 'Long Cloak',
KNIGHT_CAPE_COLOR_18: 'Orange',
KNIGHT_CAPE_COLOR_11: 'Pink',
KNIGHT_CAPE_COLOR_16: 'Purple',
KNIGHT_CAPE_COLOR_12: 'Red',
KNIGHT_CAPE_COLOR_20: 'White',
KNIGHT_CAPE_0: 'Worn Cloak',
KNIGHT_CAPE_COLOR_15: 'Yellow',
COMBO_ARMOR_SET: 'Matching Armor',
COMBO_RARE_ARMOR_SET: 'Matching Armor +',
COMBO_DUAL_ENCHANT: 'Twin Enchants',
COMBO_EQUIPMENT_TIER: 'United Equipments',
COMBO_RARE_EQUIPMENT_TIER: 'United Equipments +',
COMBO_SAME_PHYSICAL_TIER: 'United Physical',
COMBO_SAME_NAME_TIER: 'United Title',
KNIGHT_ENCHANT_0_0: 'Durability I',
KNIGHT_ENCHANT_1_0: 'Durability II',
KNIGHT_ENCHANT_2_0: 'Durability III',
KNIGHT_ENCHANT_3_0: 'Durability IV',
KNIGHT_ENCHANT_4_0: 'Durability V',
KNIGHT_ENCHANT_0_3: 'Fire Aura I',
KNIGHT_ENCHANT_1_3: 'Fire Aura II',
KNIGHT_ENCHANT_2_3: 'Fire Aura III',
KNIGHT_ENCHANT_3_3: 'Fire Aura IV',
KNIGHT_ENCHANT_4_3: 'Fire Aura V',
KNIGHT_ENCHANT_0_1: 'Sharpness I',
KNIGHT_ENCHANT_1_1: 'Sharpness II',
KNIGHT_ENCHANT_2_1: 'Sharpness III',
KNIGHT_ENCHANT_3_1: 'Sharpness IV',
KNIGHT_ENCHANT_4_1: 'Sharpness V',
KNIGHT_ENCHANT_0_4: 'Thunder Aura I',
KNIGHT_ENCHANT_1_4: 'Thunder Aura II',
KNIGHT_ENCHANT_2_4: 'Thunder Aura III',
KNIGHT_ENCHANT_3_4: 'Thunder Aura IV',
KNIGHT_ENCHANT_4_4: 'Thunder Aura V',
KNIGHT_ENCHANT_0_2: 'Water Aura I',
KNIGHT_ENCHANT_1_2: 'Water Aura II',
KNIGHT_ENCHANT_2_2: 'Water Aura III',
KNIGHT_ENCHANT_3_2: 'Water Aura IV',
KNIGHT_ENCHANT_4_2: 'Water Aura V',
KNIGHT_FACE_2_9: 'Alien',
KNIGHT_FACE_0_23: 'Angry',
KNIGHT_FACE_0_19: 'Astonished',
KNIGHT_FACE_1_11: 'Big Mustache',
KNIGHT_FACE_1_17: 'Black lips',
KNIGHT_FACE_1_5: 'Blind',
KNIGHT_FACE_0_16: 'Calm',
KNIGHT_FACE_0_1000: 'Carrot and Pebbles',
KNIGHT_FACE_3_4: 'Cat',
KNIGHT_FACE_0_30: 'Chocked',
KNIGHT_FACE_2_1: 'Clown',
KNIGHT_FACE_0_25: 'Confident',
KNIGHT_FACE_0_1: 'Contempt',
KNIGHT_FACE_0_3: 'Contempt (Old)',
KNIGHT_FACE_2_11: 'Corrupt',
KNIGHT_FACE_1_7: 'Crying',
KNIGHT_FACE_2_0: 'Cute Eyes',
KNIGHT_FACE_2_6: 'Cyclops',
KNIGHT_FACE_1_9: 'Dead',
KNIGHT_FACE_2_15: 'Dead',
KNIGHT_FACE_0_20: 'Delighted',
KNIGHT_FACE_0_14: 'Determined',
KNIGHT_FACE_3_5: 'Disfigured',
KNIGHT_FACE_0_31: 'Drooling',
KNIGHT_FACE_1_10: 'Dwarf',
KNIGHT_FACE_2_1000: 'Elf',
KNIGHT_FACE_1_0: 'Emotionless',
KNIGHT_FACE_2_4: 'Evil',
KNIGHT_FACE_0_6: 'Fake Dumb',
KNIGHT_FACE_0_11: 'Fake Smile',
KNIGHT_FACE_4_3: 'Famous Snail',
KNIGHT_FACE_1_1: 'Flirtatious',
KNIGHT_FACE_0_18: 'Flirty',
KNIGHT_FACE_0_10: 'Fmall Fmile',
KNIGHT_FACE_2_14: 'Frog',
KNIGHT_FACE_0_28: 'Frowning',
KNIGHT_FACE_1_16: 'Furious',
KNIGHT_FACE_2_13: 'Good Dog',
KNIGHT_FACE_0_5: 'Gray Beard',
KNIGHT_FACE_1_20: 'Greedy',
KNIGHT_FACE_0_4: 'Happy',
KNIGHT_FACE_2_10: 'Happy Cyclops',
KNIGHT_FACE_1_3: 'Heterochromia',
KNIGHT_FACE_4_2: 'Hidden Evil',
KNIGHT_FACE_0_32: 'Joyful',
KNIGHT_FACE_2_3: 'Known Wizard',
KNIGHT_FACE_4_0: 'Light Eyes',
KNIGHT_FACE_1_4: 'Light Makeup',
KNIGHT_FACE_2_2: 'Lizard',
KNIGHT_FACE_4_1000: 'Magic White Beard',
KNIGHT_FACE_3_2: 'Medium',
KNIGHT_FACE_1_13: 'Mono Brow',
KNIGHT_FACE_3_0: 'Monster',
KNIGHT_FACE_4_1: 'Mouth Hole',
KNIGHT_FACE_1_8: 'Mute Crying',
KNIGHT_FACE_1_12: 'Old White Beard',
KNIGHT_FACE_1_6: 'One-Eyed',
KNIGHT_FACE_3_1: 'Orc',
KNIGHT_FACE_1_2: 'Piercings',
KNIGHT_FACE_2_5: 'Pigman',
KNIGHT_FACE_0_7: 'Prankster',
KNIGHT_FACE_3_3: 'Robot',
KNIGHT_FACE_2_7: 'Scarface',
KNIGHT_FACE_0_22: 'Serious',
KNIGHT_FACE_1_14: 'Shouting',
KNIGHT_FACE_0_21: 'Sick',
KNIGHT_FACE_1_18: 'Side Glance',
KNIGHT_FACE_1_19: 'Simple Mustache',
KNIGHT_FACE_0_27: 'Singing',
KNIGHT_FACE_1_15: 'Sleepy',
KNIGHT_FACE_0_29: 'Sly',
KNIGHT_FACE_0_17: 'Small Mustache',
KNIGHT_FACE_0_26: 'Small Shock',
KNIGHT_FACE_0_2: 'Small Smile',
KNIGHT_FACE_0_8: 'Snoring',
KNIGHT_FACE_0_9: 'Suprised',
KNIGHT_FACE_0_12: 'Unhappy',
KNIGHT_FACE_2_12: 'Vampire',
KNIGHT_FACE_2_8: 'Werewolf',
KNIGHT_FACE_0_24: 'Whistling',
KNIGHT_FACE_0_15: 'Wink',
KNIGHT_FACE_0_0: 'Worried',
KNIGHT_FACE_0_13: 'Yawning',
KNIGHT_HELMET_0_2: 'Barbarian',
KNIGHT_HELMET_0_3: 'Barbarian (Bones)',
KNIGHT_HELMET_2_0: 'Bronze',
KNIGHT_HELMET_2_1: 'Bronze (Heavy)',
KNIGHT_HELMET_1_0: 'Copper',
KNIGHT_HELMET_1_1: 'Copper (Heavy)',
KNIGHT_HELMET_3_0: 'Gold',
KNIGHT_HELMET_3_1: 'Gold (Heavy)',
KNIGHT_HELMET_1_2: 'Iron',
KNIGHT_HELMET_1_3: 'Iron (Heavy)',
KNIGHT_HELMET_0_0: 'Leather',
KNIGHT_HELMET_3_2: 'Mithril',
KNIGHT_HELMET_3_3: 'Mithril (Heavy)',
KNIGHT_HELMET_4_2: 'Obsidian',
KNIGHT_HELMET_4_3: 'Obsidian (Heavy)',
KNIGHT_HELMET_4_0: 'Orichalcum',
KNIGHT_HELMET_4_1: 'Orichalcum (Heavy)',
KNIGHT_HELMET_2_2: 'Silver',
KNIGHT_HELMET_2_3: 'Silver (Heavy)',
KNIGHT_HELMET_0_1: 'Tanned Leather',
KNIGHT_MAIN_2_1: 'Bronze Axe',
KNIGHT_MAIN_2_2: 'Bronze Dagger',
KNIGHT_MAIN_2_0: 'Bronze Long Sword',
KNIGHT_MAIN_0_3: 'Club',
KNIGHT_MAIN_1_2: 'Copper Hammer',
KNIGHT_MAIN_1_1: 'Copper Mace',
KNIGHT_MAIN_1_0: 'Copper Sword',
KNIGHT_MAIN_3_1: 'Gold Great Sword',
KNIGHT_MAIN_3_0: 'Gold Hammer',
KNIGHT_MAIN_3_2: 'Gold Long Sword',
KNIGHT_MAIN_0_5: 'Great Sword',
KNIGHT_MAIN_1_5: 'Iron Broadsword',
KNIGHT_MAIN_1_3: 'Iron Mace',
KNIGHT_MAIN_1_4: 'Iron Scourge',
KNIGHT_MAIN_0_1: 'Long Sword',
KNIGHT_MAIN_3_4: 'Mithril Great Sword',
KNIGHT_MAIN_3_5: 'Mithril Rapier',
KNIGHT_MAIN_3_3: 'Mithril Scimitar',
KNIGHT_MAIN_4_5: 'Obsidian Falchion',
KNIGHT_MAIN_4_3: 'Obsidian Katana',
KNIGHT_MAIN_4_4: 'Obsidian Scythe',
KNIGHT_MAIN_4_0: 'Ori. Broadsword',
KNIGHT_MAIN_4_2: 'Ori. Club',
KNIGHT_MAIN_4_1: 'Ori. Halberd',
KNIGHT_MAIN_0_2: 'Scimitar',
KNIGHT_MAIN_2_3: 'Silver Long Sword',
KNIGHT_MAIN_2_5: 'Silver Sai',
KNIGHT_MAIN_2_4: 'Silver Spear',
KNIGHT_MAIN_0_4: 'Spear',
KNIGHT_MAIN_0_0: 'Wooden Pole',
KNIGHT_NOSET: 'No Set',
KNIGHT_OFF_2_1: 'Bronze Axe',
KNIGHT_OFF_2_2: 'Bronze Dagger',
KNIGHT_OFF_2_0: 'Bronze T. Shield',
KNIGHT_OFF_0_3: 'Club',
KNIGHT_OFF_1_2: 'Copper Dagger',
KNIGHT_OFF_1_0: 'Copper S. Sword',
KNIGHT_OFF_1_1: 'Copper Shield',
KNIGHT_OFF_0_2: 'Dagger',
KNIGHT_OFF_3_1: 'Gold Hammer',
KNIGHT_OFF_3_0: 'Gold Shield',
KNIGHT_OFF_3_2: 'Gold Short Sword',
KNIGHT_OFF_1_5: 'Iron Scourge',
KNIGHT_OFF_1_3: 'Iron Shield',
KNIGHT_OFF_1_4: 'Iron Tower Shield',
KNIGHT_OFF_3_3: 'Mithril Dagger',
KNIGHT_OFF_3_5: 'Mithril Kunai',
KNIGHT_OFF_3_4: 'Mithril Shield',
KNIGHT_OFF_4_5: 'Obsidian Scimitar',
KNIGHT_OFF_4_4: 'Obsidian Sickle',
KNIGHT_OFF_4_3: 'Obsidian Wakizashi',
KNIGHT_OFF_4_2: 'Ori. Axe',
KNIGHT_OFF_4_1: 'Ori. Scourge',
KNIGHT_OFF_4_0: 'Ori. Shield',
KNIGHT_OFF_0_5: 'Shield',
KNIGHT_OFF_0_4: 'Short Sword',
KNIGHT_OFF_2_5: 'Silver Sai',
KNIGHT_OFF_2_3: 'Silver Shield',
KNIGHT_OFF_2_4: 'Silver Short Sword',
KNIGHT_OFF_0_0: 'Wooden Shield',
KNIGHT_OFF_0_1: 'Wooden T. Shield',
KNIGHT_PET_0_1001: 'Beetle',
KNIGHT_PET_0_0: 'Cat',
KNIGHT_PET_0_3: 'Chicken',
KNIGHT_PET_1_1001: 'Clown Fish',
KNIGHT_PET_2_1001: 'Crab',
KNIGHT_PET_4_3: 'Deedee',
KNIGHT_PET_0_1: 'Dog',
KNIGHT_PET_3_2: 'EatAll',
KNIGHT_PET_2_4: 'Fairy',
KNIGHT_PET_1_2: 'Flower Spirit',
KNIGHT_PET_2_3: 'Frog',
KNIGHT_PET_2_1: 'Ghost',
KNIGHT_PET_1_1000: 'GingerBread',
KNIGHT_PET_2_0: 'Goblin',
KNIGHT_PET_4_4: 'Godzolla',
KNIGHT_PET_4_0: 'Golem',
KNIGHT_PET_4_1: 'Lizard',
KNIGHT_PET_0_4: 'Llama',
KNIGHT_PET_3_1: 'Magic Cactus',
KNIGHT_PET_1_3: 'Monkey',
KNIGHT_PET_2_2: 'Monshroom',
KNIGHT_PET_3_3: 'Otter',
KNIGHT_PET_1_4: 'Panda',
KNIGHT_PET_3_1001: 'Parrot',
KNIGHT_PET_0_1000: 'Pinguin',
KNIGHT_PET_4_2: 'Pixelchu',
KNIGHT_PET_3_1000: 'Present',
KNIGHT_PET_0_2: 'Rabbit',
KNIGHT_PET_2_1000: 'Reindeer',
KNIGHT_PET_1_1: 'Slime',
KNIGHT_PET_1_0: 'Snail',
KNIGHT_PET_4_1001: 'Tiny Sun',
KNIGHT_PET_3_0: 'Turtle',
KNIGHT_PET_4_1000: 'Winter Ent',
KNIGHT_PET_3_4: 'Wolf',
KNIGHT_SET_4: 'Angel',
KNIGHT_SET_0: 'Baker',
KNIGHT_SET_13: 'BlackSmith',
KNIGHT_SET_6: 'Cat',
KNIGHT_SET_5: 'Devil',
KNIGHT_SET_7: 'Dog',
KNIGHT_SET_23: 'EatAll Panoply',
KNIGHT_SET_15: 'Frog',
KNIGHT_SET_1: 'Joker',
KNIGHT_SET_11: 'King',
KNIGHT_SET_9: 'Lizard',
KNIGHT_SET_2: 'Medium',
KNIGHT_SET_16: 'Midas',
KNIGHT_SET_12: 'Momochang',
KNIGHT_SET_17: 'Night Hero',
KNIGHT_SET_10: 'Orc',
KNIGHT_SET_22: 'Pirate',
KNIGHT_SET_3: 'Robot',
KNIGHT_SET_21: 'Santa Claus',
KNIGHT_SET_18: 'Snowman',
KNIGHT_SET_14: 'Wizard',
KNIGHT_SET_8: 'Wolf',
KNIGHT_SET_20: 'Xmas Elf',
KNIGHT_SET_19: 'Zombie',
SHINY_3: 'Crimson Shine',
SHINY_4: 'Dark Shine',
SHINY_2: 'Golden Shine',
SHINY_0: 'No Shine',
SHINY_1: 'Silver Shine',
KNIGHT_SPECIAL_ARMOR_0_0: 'Baker Apron',
KNIGHT_SPECIAL_ARMOR_0_1: 'Blacksmith Apron',
KNIGHT_SPECIAL_ARMOR_0_1000: 'Compact Snow',
KNIGHT_SPECIAL_ARMOR_4_1: 'Devil\'s Mutation',
KNIGHT_SPECIAL_ARMOR_4_0: 'Divine Outfit',
KNIGHT_SPECIAL_ARMOR_2_2: 'EatAll Chestplate',
KNIGHT_SPECIAL_ARMOR_1_2: 'Filibuster Outfit',
KNIGHT_SPECIAL_ARMOR_2_1: 'Light Chestplate',
KNIGHT_SPECIAL_ARMOR_1_0: 'Minstrel Outfit',
KNIGHT_SPECIAL_ARMOR_2_0: 'Oracle Robe',
KNIGHT_SPECIAL_ARMOR_3_0: 'Robot Armor',
KNIGHT_SPECIAL_ARMOR_0_2: 'Rotten Clothes',
KNIGHT_SPECIAL_ARMOR_4_2: 'Slimy Slug',
KNIGHT_SPECIAL_ARMOR_3_1: 'Stealth Armor',
KNIGHT_SPECIAL_ARMOR_1_1: 'Wizard Robe',
KNIGHT_SPECIAL_ARMOR_2_1000: 'Xmas Elf Outfit',
KNIGHT_SPECIAL_ARMOR_4_1000: 'Xmas Outfit',
KNIGHT_SPECIAL_HELMET_4_1: 'Aureole',
KNIGHT_SPECIAL_HELMET_2_0: 'Cat Ears',
KNIGHT_SPECIAL_HELMET_0_0: 'Chef Hat',
KNIGHT_SPECIAL_HELMET_4_0: 'Crown',
KNIGHT_SPECIAL_HELMET_0_2: 'Cubic hairstyle',
KNIGHT_SPECIAL_HELMET_4_2: 'Devil\'s Horns',
KNIGHT_SPECIAL_HELMET_2_1: 'Dog Ears',
KNIGHT_SPECIAL_HELMET_2_5: 'EatAll Cap',
KNIGHT_SPECIAL_HELMET_1_1: 'Hat of Choice',
KNIGHT_SPECIAL_HELMET_1_0: 'Joker Hat',
KNIGHT_SPECIAL_HELMET_2_3: 'Lizard Horns',
KNIGHT_SPECIAL_HELMET_2_2: 'Oracle Veil',
KNIGHT_SPECIAL_HELMET_2_4: 'Orc Ears',
KNIGHT_SPECIAL_HELMET_1_2: 'Pirate Tricorn',
KNIGHT_SPECIAL_HELMET_3_0: 'Robot Antennas',
KNIGHT_SPECIAL_HELMET_0_1: 'Shiny Bald Head',
KNIGHT_SPECIAL_HELMET_4_3: 'Slimy Mutation',
KNIGHT_SPECIAL_HELMET_3_2: 'Stealth Helmet',
KNIGHT_SPECIAL_HELMET_0_1000: 'Top Hat',
KNIGHT_SPECIAL_HELMET_3_1: 'Wolf Ears',
KNIGHT_SPECIAL_HELMET_2_1000: 'Xmas Elf Hat',
KNIGHT_SPECIAL_HELMET_4_1000: 'Xmas Hat',
KNIGHT_SPECIAL_MAIN_0_1: 'Blacksmith Hammer',
KNIGHT_SPECIAL_MAIN_0_1000: 'Broom',
KNIGHT_SPECIAL_MAIN_2_1000: 'Candy Cane',
KNIGHT_SPECIAL_MAIN_2_0: 'Crystal Ball',
KNIGHT_SPECIAL_MAIN_1_2: 'Cutlass',
KNIGHT_SPECIAL_MAIN_4_1: 'Demonic Trident',
KNIGHT_SPECIAL_MAIN_2_2: 'EatAll Hammer',
KNIGHT_SPECIAL_MAIN_1_1: 'Griffin Sword',
KNIGHT_SPECIAL_MAIN_4_0: 'Holy Blade',
KNIGHT_SPECIAL_MAIN_3_2: 'Hook Pistol',
KNIGHT_SPECIAL_MAIN_1_0: 'Jugglin Pin',
KNIGHT_SPECIAL_MAIN_3_0: 'Laser Gun',
KNIGHT_SPECIAL_MAIN_2_1: 'Masamune',
KNIGHT_SPECIAL_MAIN_0_0: 'Rolling Pin',
KNIGHT_SPECIAL_MAIN_3_1: 'Scepter',
KNIGHT_SPECIAL_MAIN_0_2: 'Stone Sword',
KNIGHT_SPECIAL_MAIN_4_2: 'USB Spear',
KNIGHT_SPECIAL_MAIN_4_1000: 'Xmas Bell',
KNIGHT_SPECIAL_OFF_0_0: 'Baguette',
KNIGHT_SPECIAL_OFF_4_1: 'Demonic Whip',
KNIGHT_SPECIAL_OFF_3_0: 'Drill Hand',
KNIGHT_SPECIAL_OFF_2_2: 'EatAll Shield',
KNIGHT_SPECIAL_OFF_1_2: 'Flintlock Pistol',
KNIGHT_SPECIAL_OFF_3_1: 'Holy Grenade',
KNIGHT_SPECIAL_OFF_4_0: 'Holy Tome',
KNIGHT_SPECIAL_OFF_4_2: 'Joystick',
KNIGHT_SPECIAL_OFF_1_1: 'Magic Wand',
KNIGHT_SPECIAL_OFF_0_1: 'Pliers',
KNIGHT_SPECIAL_OFF_0_1000: 'Snowball',
KNIGHT_SPECIAL_OFF_2_1: 'Star Shield',
KNIGHT_SPECIAL_OFF_3_2: 'Stealth Boomerang',
KNIGHT_SPECIAL_OFF_0_2: 'Stone Pickaxe',
KNIGHT_SPECIAL_OFF_2_0: 'Tambourine',
KNIGHT_SPECIAL_OFF_1_0: 'Tarot Cards',
KNIGHT_SPECIAL_OFF_4_1000: 'Xmas Hood',
KNIGHT_SPECIAL_OFF_2_1000: 'Xmax Stocking',
KNIGHT_NAME_0_0: 'Eugene',
KNIGHT_NAME_0_1: 'Nina',
KNIGHT_NAME_0_2: 'Maria',
KNIGHT_NAME_0_3: 'Clement',
KNIGHT_NAME_0_4: 'Gabrielle',
KNIGHT_NAME_0_5: 'Cyril',
KNIGHT_NAME_0_6: 'Adrian',
KNIGHT_NAME_0_7: 'Victor',
KNIGHT_NAME_0_8: 'Paul',
KNIGHT_NAME_0_9: 'Mathilda',
KNIGHT_NAME_0_10: 'Sophia',
KNIGHT_NAME_0_11: 'Emmanuel',
KNIGHT_NAME_0_12: 'Thomas',
KNIGHT_NAME_0_13: 'Eric',
KNIGHT_NAME_0_14: 'Jessie',
KNIGHT_NAME_0_15: 'Jessica',
KNIGHT_NAME_0_16: 'Lola',
KNIGHT_NAME_0_17: 'Charlie',
KNIGHT_NAME_0_18: 'Charles',
KNIGHT_NAME_0_19: 'Andy',
KNIGHT_NAME_0_20: 'Mark',
KNIGHT_NAME_0_21: 'Lesley',
KNIGHT_NAME_0_22: 'Mariam',
KNIGHT_NAME_0_23: 'Martin',
KNIGHT_NAME_0_24: 'Kevin',
KNIGHT_NAME_0_25: 'Franck',
KNIGHT_NAME_0_26: 'Lucas',
KNIGHT_NAME_0_27: 'Sandy',
KNIGHT_NAME_0_28: 'Lucile',
KNIGHT_NAME_0_29: 'Louisa',
KNIGHT_NAME_0_30: 'Pauline',
KNIGHT_NAME_0_31: 'Remi',
KNIGHT_NAME_0_32: 'Sorley',
KNIGHT_NAME_0_33: 'Elouise',
KNIGHT_NAME_0_34: 'Denys',
KNIGHT_NAME_0_35: 'Gregory',
KNIGHT_NAME_0_36: 'Nicholas',
KNIGHT_NAME_0_37: 'Roxane',
KNIGHT_NAME_0_38: 'Michel',
KNIGHT_NAME_0_39: 'Nichole',
KNIGHT_NAME_0_40: 'Evette',
KNIGHT_NAME_0_41: 'Quinton',
KNIGHT_NAME_0_42: 'Serge',
KNIGHT_NAME_0_43: 'Alice',
KNIGHT_NAME_0_44: 'Guilleme',
KNIGHT_NAME_0_45: 'Yann',
KNIGHT_NAME_0_46: 'Mustapha',
KNIGHT_NAME_0_47: 'Sofiane',
KNIGHT_NAME_0_48: 'Camille',
KNIGHT_NAME_0_49: 'Cloe',
KNIGHT_NAME_0_50: 'Felix',
KNIGHT_NAME_0_51: 'Paula',
KNIGHT_NAME_0_52: 'Karine',
KNIGHT_NAME_0_53: 'Julie',
KNIGHT_NAME_0_54: 'Patricia',
KNIGHT_NAME_0_55: 'Jean-Claude',
KNIGHT_NAME_0_56: 'Isabelle',
KNIGHT_NAME_0_57: 'Simon',
KNIGHT_NAME_0_58: 'Jean-Michel',
KNIGHT_NAME_0_59: 'Sylvie',
KNIGHT_NAME_1_0: 'Henry',
KNIGHT_NAME_1_1: 'Robert',
KNIGHT_NAME_1_2: 'William',
KNIGHT_NAME_1_3: 'Rodrigo',
KNIGHT_NAME_1_4: 'Hugues',
KNIGHT_NAME_1_5: 'Guy',
KNIGHT_NAME_1_6: 'Ulrich',
KNIGHT_NAME_1_7: 'James',
KNIGHT_NAME_1_8: 'Geoffroi',
KNIGHT_NAME_1_9: 'Bertrand',
KNIGHT_NAME_1_10: 'Edward',
KNIGHT_NAME_1_11: 'Jean',
KNIGHT_NAME_1_12: 'Gottfried',
KNIGHT_NAME_1_13: 'Parn',
KNIGHT_NAME_1_14: 'Ryner',
KNIGHT_NAME_1_15: 'NuWeb',
KNIGHT_NAME_1_16: 'Julian',
KNIGHT_NAME_1_17: 'Julia',
KNIGHT_NAME_1_18: 'Lisette',
KNIGHT_NAME_1_19: 'Louis',
KNIGHT_NAME_1_20: 'Ichigo',
KNIGHT_NAME_1_21: 'Rukia',
KNIGHT_NAME_1_22: 'Harry',
KNIGHT_NAME_1_23: 'Achilles',
KNIGHT_NAME_1_24: 'Hector',
KNIGHT_NAME_1_25: 'Janis',
KNIGHT_NAME_2_0: 'Richard',
KNIGHT_NAME_2_1: 'Alexander',
KNIGHT_NAME_2_2: 'Joan',
KNIGHT_NAME_2_3: 'Canigz',
KNIGHT_NAME_2_4: 'Uranie',
KNIGHT_NAME_2_5: 'Britanouille',
KNIGHT_NAME_2_6: 'Mizuki_Okami',
KNIGHT_NAME_2_7: 'Kirito',
KNIGHT_NAME_2_8: 'Cecily',
KNIGHT_NAME_2_9: 'Arslan',
KNIGHT_NAME_2_10: 'Yuri',
KNIGHT_NAME_2_11: 'Flynn',
KNIGHT_NAME_2_12: 'Anakin',
KNIGHT_NAME_2_13: 'Mace',
KNIGHT_NAME_2_14: 'Luke',
KNIGHT_NAME_2_15: 'Obi-Wan',
KNIGHT_NAME_2_16: 'BlackStar',
KNIGHT_NAME_2_17: 'Tartopoiro',
KNIGHT_NAME_2_18: 'Redwin le Nain',
KNIGHT_NAME_2_19: 'Lavsa',
KNIGHT_NAME_2_20: 'Asuna',
KNIGHT_NAME_2_21: 'Glenn',
KNIGHT_NAME_2_22: 'Dave',
KNIGHT_NAME_3_0: 'Lectamenop',
KNIGHT_NAME_3_1: 'Liryc',
KNIGHT_NAME_3_2: 'Peugeumeu',
KNIGHT_NAME_3_3: 'Loutre',
KNIGHT_NAME_3_4: 'Yelahw',
KNIGHT_NAME_3_5: 'Jokarwent',
KNIGHT_NAME_3_6: 'Impxay',
KNIGHT_NAME_3_7: 'Leroy',
KNIGHT_NAME_3_8: 'Maximilian',
KNIGHT_NAME_3_9: 'Monica',
KNIGHT_NAME_3_10: 'D\'artagnan',
KNIGHT_NAME_3_11: 'Kellaris',
KNIGHT_NAME_3_12: 'Midas',
KNIGHT_NAME_3_13: 'Bruce',
KNIGHT_NAME_3_14: 'Seud',
KNIGHT_NAME_3_15: 'Ryssth',
KNIGHT_NAME_3_16: 'AlphaImorus',
KNIGHT_NAME_3_17: 'Kmagnum',
KNIGHT_NAME_3_18: 'Creepoguro',
KNIGHT_NAME_3_19: 'SioFreed',
KNIGHT_NAME_4_0: 'Momochang',
KNIGHT_NAME_4_1: 'Doublenom',
KNIGHT_NAME_4_2: 'Kairanoob',
KNIGHT_NAME_4_3: 'Arthur',
KNIGHT_NAME_4_4: 'Bahia',
KNIGHT_NAME_4_5: 'Yoda',
KNIGHT_NAME_4_6: 'Bastet',
KNIGHT_NAME_4_7: 'Conan',
KNIGHT_NAME_4_8: 'Claus',
KNIGHT_TRAIT_0_0: 'Young',
KNIGHT_TRAIT_0_1: 'Middle-aged',
KNIGHT_TRAIT_0_2: 'Old',
KNIGHT_TRAIT_0_3: 'Weak',
KNIGHT_TRAIT_0_4: 'Small',
KNIGHT_TRAIT_0_5: 'Big',
KNIGHT_TRAIT_0_6: 'Tall',
KNIGHT_TRAIT_0_7: 'Grumpy',
KNIGHT_TRAIT_0_8: 'Low',
KNIGHT_TRAIT_0_9: 'Average',
KNIGHT_TRAIT_0_10: 'Petty',
KNIGHT_TRAIT_0_11: 'Strange',
KNIGHT_TRAIT_0_12: 'Large',
KNIGHT_TRAIT_0_13: 'Insignificant',
KNIGHT_TRAIT_0_14: 'Bad',
KNIGHT_TRAIT_0_15: 'Neutral',
KNIGHT_TRAIT_0_16: 'Unfair',
KNIGHT_TRAIT_0_17: 'Disloyal',
KNIGHT_TRAIT_0_18: 'Granpa',
KNIGHT_TRAIT_0_19: 'Dumb',
KNIGHT_TRAIT_0_20: 'Gross',
KNIGHT_TRAIT_0_21: 'Vulgar',
KNIGHT_TRAIT_0_22: 'Unrefined',
KNIGHT_TRAIT_0_23: 'Rude',
KNIGHT_TRAIT_0_24: 'Greedy',
KNIGHT_TRAIT_0_25: 'Rough',
KNIGHT_TRAIT_0_26: 'Pitiful',
KNIGHT_TRAIT_0_27: 'Perverted',
KNIGHT_TRAIT_0_28: 'Ill',
KNIGHT_TRAIT_0_29: 'Nasty',
KNIGHT_TRAIT_0_30: 'Faulty',
KNIGHT_TRAIT_0_31: 'Poor',
KNIGHT_TRAIT_0_32: 'Timid',
KNIGHT_TRAIT_0_33: 'Shy',
KNIGHT_TRAIT_0_34: 'Scared',
KNIGHT_TRAIT_0_35: 'Fearful',
KNIGHT_TRAIT_0_36: 'Unlucky',
KNIGHT_TRAIT_0_37: 'Minor',
KNIGHT_TRAIT_0_38: 'Petrified',
KNIGHT_TRAIT_0_39: 'Paralysed',
KNIGHT_TRAIT_0_40: 'Burned',
KNIGHT_TRAIT_0_41: 'Poisoned',
KNIGHT_TRAIT_0_42: 'Alone',
KNIGHT_TRAIT_0_43: 'Daft',
KNIGHT_TRAIT_0_44: 'Fool',
KNIGHT_TRAIT_0_45: 'Lunatic',
KNIGHT_TRAIT_0_46: 'Gentle',
KNIGHT_TRAIT_0_47: 'Loud',
KNIGHT_TRAIT_0_48: 'Heavy',
KNIGHT_TRAIT_0_49: 'Sissy',
KNIGHT_TRAIT_0_50: 'Slow',
KNIGHT_TRAIT_0_51: 'Leisurely',
KNIGHT_TRAIT_0_52: 'Tardy',
KNIGHT_TRAIT_0_53: 'Displeased',
KNIGHT_TRAIT_0_54: 'Displeasing',
KNIGHT_TRAIT_0_55: 'Distasteful',
KNIGHT_TRAIT_0_56: 'Annoying',
KNIGHT_TRAIT_0_57: 'Boring',
KNIGHT_TRAIT_0_58: 'Bothersome',
KNIGHT_TRAIT_0_59: 'Dull',
KNIGHT_TRAIT_0_60: 'Troublesome',
KNIGHT_TRAIT_0_61: 'Rotten',
KNIGHT_TRAIT_0_62: 'Decayed',
KNIGHT_TRAIT_0_63: 'Foul',
KNIGHT_TRAIT_0_64: 'Blind',
KNIGHT_TRAIT_0_65: 'Deaf',
KNIGHT_TRAIT_0_66: 'Voiceless',
KNIGHT_TRAIT_0_67: 'Sick',
KNIGHT_TRAIT_0_68: 'Unwell',
KNIGHT_TRAIT_0_69: 'Sickly',
KNIGHT_TRAIT_0_70: 'Oblivious',
KNIGHT_TRAIT_0_71: 'Adorable',
KNIGHT_TRAIT_0_72: 'Amused',
KNIGHT_TRAIT_0_73: 'Agreeable',
KNIGHT_TRAIT_0_74: 'Anxious',
KNIGHT_TRAIT_0_75: 'Ashamed',
KNIGHT_TRAIT_0_76: 'Awful',
KNIGHT_TRAIT_0_77: 'Bewildered',
KNIGHT_TRAIT_0_78: 'Blushing',
KNIGHT_TRAIT_0_79: 'Bored',
KNIGHT_TRAIT_0_80: 'Busy',
KNIGHT_TRAIT_0_81: 'Calm',
KNIGHT_TRAIT_0_82: 'Cloudy',
KNIGHT_TRAIT_0_83: 'Clumsy',
KNIGHT_TRAIT_0_84: 'Concerned',
KNIGHT_TRAIT_0_85: 'Condemned',
KNIGHT_TRAIT_0_86: 'Confused',
KNIGHT_TRAIT_0_87: 'Creepy',
KNIGHT_TRAIT_0_88: 'Curious',
KNIGHT_TRAIT_0_89: 'Cute',
KNIGHT_TRAIT_0_90: 'Defeated',
KNIGHT_TRAIT_0_91: 'Depressed',
KNIGHT_TRAIT_0_92: 'Different',
KNIGHT_TRAIT_0_93: 'Disgusted',
KNIGHT_TRAIT_0_94: 'Disturbed',
KNIGHT_TRAIT_0_95: 'Dizzy',
KNIGHT_TRAIT_0_96: 'Doubtful',
KNIGHT_TRAIT_0_97: 'Drab',
KNIGHT_TRAIT_0_98: 'Eager',
KNIGHT_TRAIT_0_99: 'Easy',
KNIGHT_TRAIT_0_100: 'Elated',
KNIGHT_TRAIT_0_101: 'Embarrassed',
KNIGHT_TRAIT_0_102: 'Envious',
KNIGHT_TRAIT_0_103: 'Filthy',
KNIGHT_TRAIT_0_104: 'Foolish',
KNIGHT_TRAIT_0_105: 'Fragile',
KNIGHT_TRAIT_0_106: 'Frail',
KNIGHT_TRAIT_0_107: 'Frantic',
KNIGHT_TRAIT_0_108: 'Friendly',
KNIGHT_TRAIT_0_109: 'Frightened',
KNIGHT_TRAIT_0_110: 'Funny',
KNIGHT_TRAIT_0_111: 'Grieving',
KNIGHT_TRAIT_0_112: 'Grotesque',
KNIGHT_TRAIT_0_113: 'Helpless',
KNIGHT_TRAIT_0_114: 'Hilarious',
KNIGHT_TRAIT_0_115: 'Hungry',
KNIGHT_TRAIT_0_116: 'Hurt',
KNIGHT_TRAIT_0_117: 'Innocent',
KNIGHT_TRAIT_0_118: 'Jealous',
KNIGHT_TRAIT_0_119: 'Jittery',
KNIGHT_TRAIT_0_120: 'Jolly',
KNIGHT_TRAIT_0_121: 'Joyous',
KNIGHT_TRAIT_0_122: 'Lazy',
KNIGHT_TRAIT_0_123: 'Lively',
KNIGHT_TRAIT_0_124: 'Lonely',
KNIGHT_TRAIT_0_125: 'Lovely',
KNIGHT_TRAIT_0_126: 'Motionless',
KNIGHT_TRAIT_0_127: 'Muddy',
KNIGHT_TRAIT_0_128: 'Worst',
KNIGHT_TRAIT_0_129: 'Naughty',
KNIGHT_TRAIT_0_130: 'Nervous',
KNIGHT_TRAIT_0_131: 'Nutty',
KNIGHT_TRAIT_0_132: 'Obedient',
KNIGHT_TRAIT_0_133: 'Obnoxious',
KNIGHT_TRAIT_0_134: 'Odd',
KNIGHT_TRAIT_0_135: 'Panicky',
KNIGHT_TRAIT_0_136: 'Plain',
KNIGHT_TRAIT_0_137: 'Pleasant',
KNIGHT_TRAIT_0_138: 'Putrid',
KNIGHT_TRAIT_0_139: 'Puzzled',
KNIGHT_TRAIT_0_140: 'Relieved',
KNIGHT_TRAIT_0_141: 'Repulsive',
KNIGHT_TRAIT_0_142: 'Selfish',
KNIGHT_TRAIT_0_143: 'Silly',
KNIGHT_TRAIT_0_144: 'Sleepy',
KNIGHT_TRAIT_0_145: 'Smiling',
KNIGHT_TRAIT_0_146: 'Stupid',
KNIGHT_TRAIT_0_147: 'Tense',
KNIGHT_TRAIT_0_148: 'Terrible',
KNIGHT_TRAIT_0_149: 'Thankful',
KNIGHT_TRAIT_0_150: 'Thoughtless',
KNIGHT_TRAIT_0_151: 'Tired',
KNIGHT_TRAIT_0_152: 'Troubled',
KNIGHT_TRAIT_0_153: 'Ugly',
KNIGHT_TRAIT_0_154: 'Uninterested',
KNIGHT_TRAIT_0_155: 'Unsightly',
KNIGHT_TRAIT_0_156: 'Upset',
KNIGHT_TRAIT_0_157: 'Uptight',
KNIGHT_TRAIT_0_158: 'Weary',
KNIGHT_TRAIT_0_159: 'Wide-eyed',
KNIGHT_TRAIT_0_160: 'Worried',
KNIGHT_TRAIT_0_161: 'Wrong',
KNIGHT_TRAIT_0_162: 'Crying',
KNIGHT_TRAIT_0_163: 'Heinous',
KNIGHT_TRAIT_0_164: 'Vicious',
KNIGHT_TRAIT_0_165: 'Gay',
KNIGHT_TRAIT_0_166: 'Lesbian',
KNIGHT_TRAIT_0_167: 'Grown-up',
KNIGHT_TRAIT_0_168: 'Worthless',
KNIGHT_TRAIT_0_169: 'Stuned',
KNIGHT_TRAIT_0_170: 'Inadequate',
KNIGHT_TRAIT_0_171: 'Culprit',
KNIGHT_TRAIT_0_172: 'Guilty',
KNIGHT_TRAIT_0_173: 'Sinful',
KNIGHT_TRAIT_0_174: 'Crippled',
KNIGHT_TRAIT_0_175: 'Disabled',
KNIGHT_TRAIT_0_176: 'Tiring',
KNIGHT_TRAIT_0_177: 'Struggling',
KNIGHT_TRAIT_0_178: 'Idle',
KNIGHT_TRAIT_0_179: 'Follower',
KNIGHT_TRAIT_0_180: 'Sinewy',
KNIGHT_TRAIT_0_181: 'Skinny',
KNIGHT_TRAIT_0_182: 'Thin',
KNIGHT_TRAIT_0_183: 'Lean',
KNIGHT_TRAIT_0_184: 'Lousy',
KNIGHT_TRAIT_0_185: 'French',
KNIGHT_TRAIT_0_186: 'English',
KNIGHT_TRAIT_0_187: 'Spanish',
KNIGHT_TRAIT_0_188: 'Chinese',
KNIGHT_TRAIT_0_189: 'Japanese',
KNIGHT_TRAIT_0_190: 'Spouse',
KNIGHT_TRAIT_0_191: 'Child',
KNIGHT_TRAIT_0_192: 'Passive',
KNIGHT_TRAIT_0_193: 'Sidekick',
KNIGHT_TRAIT_0_194: 'Girly',
KNIGHT_TRAIT_0_195: 'Thunderstruck',
KNIGHT_TRAIT_0_196: 'Tenderized',
KNIGHT_TRAIT_0_197: 'Blue',
KNIGHT_TRAIT_0_198: 'Red',
KNIGHT_TRAIT_0_199: 'Yellow',
KNIGHT_TRAIT_0_200: 'Orange',
KNIGHT_TRAIT_0_201: 'Green',
KNIGHT_TRAIT_0_202: 'Gray',
KNIGHT_TRAIT_0_203: 'Gaudy',
KNIGHT_TRAIT_0_204: 'Stinking',
KNIGHT_TRAIT_0_205: 'Abandoned',
KNIGHT_TRAIT_0_206: 'Substandard',
KNIGHT_TRAIT_0_207: 'Second Class',
KNIGHT_TRAIT_0_208: 'Eater',
KNIGHT_TRAIT_0_209: 'Hater',
KNIGHT_TRAIT_0_210: 'Peaceful',
KNIGHT_TRAIT_0_211: 'Speechless',
KNIGHT_TRAIT_0_212: 'Horny',
KNIGHT_TRAIT_0_213: 'Powerless',
KNIGHT_TRAIT_0_214: 'Toothless',
KNIGHT_TRAIT_0_215: 'Feminist',
KNIGHT_TRAIT_0_216: 'Methodic',
KNIGHT_TRAIT_0_217: 'Delightful',
KNIGHT_TRAIT_1_0: 'Determined',
KNIGHT_TRAIT_1_1: 'Elegant',
KNIGHT_TRAIT_1_2: 'Encouraging',
KNIGHT_TRAIT_1_3: 'Energetic',
KNIGHT_TRAIT_1_4: 'Enthusiastic',
KNIGHT_TRAIT_1_5: 'Pretty',
KNIGHT_TRAIT_1_6: 'Sexy',
KNIGHT_TRAIT_1_7: 'Poisonous',
KNIGHT_TRAIT_1_8: 'Fine',
KNIGHT_TRAIT_1_9: 'Crafty',
KNIGHT_TRAIT_1_10: 'Smart',
KNIGHT_TRAIT_1_11: 'Good',
KNIGHT_TRAIT_1_12: 'Chaotic',
KNIGHT_TRAIT_1_13: 'Loyal',
KNIGHT_TRAIT_1_14: 'Treacherous',
KNIGHT_TRAIT_1_15: 'Fair',
KNIGHT_TRAIT_1_16: 'Shocking',
KNIGHT_TRAIT_1_17: 'Sacrificial',
KNIGHT_TRAIT_1_18: 'Wicked',
KNIGHT_TRAIT_1_19: 'Rich',
KNIGHT_TRAIT_1_20: 'Wealthy',
KNIGHT_TRAIT_1_21: 'Strong',
KNIGHT_TRAIT_1_22: 'Scary',
KNIGHT_TRAIT_1_23: 'Fearless',
KNIGHT_TRAIT_1_24: 'Major',
KNIGHT_TRAIT_1_25: 'Schizophrenic',
KNIGHT_TRAIT_1_26: 'Psychotic',
KNIGHT_TRAIT_1_27: 'Crazy',
KNIGHT_TRAIT_1_28: 'Mad',
KNIGHT_TRAIT_1_29: 'Insane',
KNIGHT_TRAIT_1_30: 'Crazed',
KNIGHT_TRAIT_1_31: 'Benevolent',
KNIGHT_TRAIT_1_32: 'Kind',
KNIGHT_TRAIT_1_33: 'Nice',
KNIGHT_TRAIT_1_34: 'Hard',
KNIGHT_TRAIT_1_35: 'Premium',
KNIGHT_TRAIT_1_36: 'Athlete',
KNIGHT_TRAIT_1_37: 'Veteran',
KNIGHT_TRAIT_1_38: 'Truculent',
KNIGHT_TRAIT_1_39: 'Muscular',
KNIGHT_TRAIT_1_40: 'Chic',
KNIGHT_TRAIT_1_41: 'Stylish',
KNIGHT_TRAIT_1_42: 'Metaphoric',
KNIGHT_TRAIT_1_43: 'Actor',
KNIGHT_TRAIT_1_44: 'Great',
KNIGHT_TRAIT_1_45: 'Fancy',
KNIGHT_TRAIT_1_46: 'White',
KNIGHT_TRAIT_1_47: 'Black',
KNIGHT_TRAIT_1_48: 'Tough',
KNIGHT_TRAIT_1_49: 'Resistant',
KNIGHT_TRAIT_1_50: 'Quick',
KNIGHT_TRAIT_1_51: 'Fast',
KNIGHT_TRAIT_1_52: 'Swift',
KNIGHT_TRAIT_1_53: 'Speedy',
KNIGHT_TRAIT_1_54: 'Healthy',
KNIGHT_TRAIT_1_55: 'Joyful',
KNIGHT_TRAIT_1_56: 'Damned',
KNIGHT_TRAIT_1_57: 'Happy',
KNIGHT_TRAIT_1_58: 'Traitor',
KNIGHT_TRAIT_1_59: 'Villain',
KNIGHT_TRAIT_1_60: 'Bright',
KNIGHT_TRAIT_1_61: 'Adventurous',
KNIGHT_TRAIT_1_62: 'Aggressive',
KNIGHT_TRAIT_1_63: 'Alert',
KNIGHT_TRAIT_1_64: 'Arrogant',
KNIGHT_TRAIT_1_65: 'Attractive',
KNIGHT_TRAIT_1_66: 'Beautiful',
KNIGHT_TRAIT_1_67: 'Better',
KNIGHT_TRAIT_1_68: 'Brainy',
KNIGHT_TRAIT_1_69: 'Brave',
KNIGHT_TRAIT_1_70: 'Careful',
KNIGHT_TRAIT_1_71: 'Cautious',
KNIGHT_TRAIT_1_72: 'Charming',
KNIGHT_TRAIT_1_73: 'Cheerful',
KNIGHT_TRAIT_1_74: 'Clean',
KNIGHT_TRAIT_1_75: 'Clever',
KNIGHT_TRAIT_1_76: 'Colorful',
KNIGHT_TRAIT_1_77: 'Combative',
KNIGHT_TRAIT_1_78: 'Cooperative',
KNIGHT_TRAIT_1_79: 'Courageous',
KNIGHT_TRAIT_1_80: 'Cruel',
KNIGHT_TRAIT_1_81: 'Excited',
KNIGHT_TRAIT_1_82: 'Exuberant',
KNIGHT_TRAIT_1_83: 'Faithful',
KNIGHT_TRAIT_1_84: 'Defiant',
KNIGHT_TRAIT_1_85: 'Glamorous',
KNIGHT_TRAIT_1_86: 'Gorgeous',
KNIGHT_TRAIT_1_87: 'Gleaming',
KNIGHT_TRAIT_1_88: 'Graceful',
KNIGHT_TRAIT_1_89: 'Handsome',
KNIGHT_TRAIT_1_90: 'Helpful',
KNIGHT_TRAIT_1_91: 'Inquisitive',
KNIGHT_TRAIT_1_92: 'Horrible',
KNIGHT_TRAIT_1_93: 'Modern',
KNIGHT_TRAIT_1_94: 'Old-fashioned',
KNIGHT_TRAIT_1_95: 'Poised',
KNIGHT_TRAIT_1_96: 'Proud',
KNIGHT_TRAIT_1_97: 'Rational',
KNIGHT_TRAIT_1_98: 'Copper',
KNIGHT_TRAIT_1_99: 'Spotless',
KNIGHT_TRAIT_1_100: 'Thoughtful',
KNIGHT_TRAIT_1_101: 'Vivacious',
KNIGHT_TRAIT_1_102: 'Witty',
KNIGHT_TRAIT_1_103: 'Worrisome',
KNIGHT_TRAIT_1_104: 'Dexterous',
KNIGHT_TRAIT_1_105: 'Luxurious',
KNIGHT_TRAIT_1_106: 'Bastard',
KNIGHT_TRAIT_1_107: 'Rider',
KNIGHT_TRAIT_1_108: 'Independant',
KNIGHT_TRAIT_1_109: 'Merchant',
KNIGHT_TRAIT_1_110: 'Matriarch',
KNIGHT_TRAIT_1_111: 'Abnormal',
KNIGHT_TRAIT_1_112: 'Patriarch',
KNIGHT_TRAIT_1_113: 'Creative',
KNIGHT_TRAIT_1_114: 'Baby',
KNIGHT_TRAIT_1_115: 'Mayor',
KNIGHT_TRAIT_1_116: 'Father',
KNIGHT_TRAIT_1_117: 'Beaming',
KNIGHT_TRAIT_1_118: 'Boomer',
KNIGHT_TRAIT_1_119: 'Escapist',
KNIGHT_TRAIT_1_120: 'Therapist',
KNIGHT_TRAIT_1_121: 'Scientific',
KNIGHT_TRAIT_1_122: 'Sumo',
KNIGHT_TRAIT_1_123: 'Stunning',
KNIGHT_TRAIT_1_124: 'Rampaging',
KNIGHT_TRAIT_1_125: 'Wolf',
KNIGHT_TRAIT_1_126: 'Fox',
KNIGHT_TRAIT_1_127: 'Dog',
KNIGHT_TRAIT_1_128: 'Womanizer',
KNIGHT_TRAIT_1_129: 'Chicken-lover',
KNIGHT_TRAIT_1_130: 'Lizard',
KNIGHT_TRAIT_1_131: 'Seer',
KNIGHT_TRAIT_1_132: 'Clairvoyant',
KNIGHT_TRAIT_1_133: 'Natural',
KNIGHT_TRAIT_1_134: 'Left-handed',
KNIGHT_TRAIT_1_135: 'Punk',
KNIGHT_TRAIT_1_136: 'Celebrating',
KNIGHT_TRAIT_1_137: 'Generous',
KNIGHT_TRAIT_1_138: 'Agile',
KNIGHT_TRAIT_1_139: 'Acute',
KNIGHT_TRAIT_1_140: 'Dashing',
KNIGHT_TRAIT_1_141: 'Apt',
KNIGHT_TRAIT_1_142: 'Nefarious',
KNIGHT_TRAIT_2_0: 'Enchanted',
KNIGHT_TRAIT_2_1: 'Magical',
KNIGHT_TRAIT_2_2: 'Maniac',
KNIGHT_TRAIT_2_3: 'Magic',
KNIGHT_TRAIT_2_4: 'Fiery',
KNIGHT_TRAIT_2_5: 'Burning',
KNIGHT_TRAIT_2_6: 'Aquatic',
KNIGHT_TRAIT_2_7: 'Zombie',
KNIGHT_TRAIT_2_8: 'Dangerous',
KNIGHT_TRAIT_2_9: 'Electrified',
KNIGHT_TRAIT_2_10: 'Dead',
KNIGHT_TRAIT_2_11: 'Unbelievable',
KNIGHT_TRAIT_2_12: 'High',
KNIGHT_TRAIT_2_13: 'Lucky',
KNIGHT_TRAIT_2_14: 'Berserk',
KNIGHT_TRAIT_2_15: 'Psychic',
KNIGHT_TRAIT_2_16: 'Charismatic',
KNIGHT_TRAIT_2_17: 'Powerful',
KNIGHT_TRAIT_2_18: 'Potent',
KNIGHT_TRAIT_2_19: 'Mighty',
KNIGHT_TRAIT_2_20: 'Forceful',
KNIGHT_TRAIT_2_21: 'Flying',
KNIGHT_TRAIT_2_22: 'Cursed',
KNIGHT_TRAIT_2_23: 'Bloody',
KNIGHT_TRAIT_2_24: 'Dark',
KNIGHT_TRAIT_2_25: 'Famous',
KNIGHT_TRAIT_2_26: 'Fantastic',
KNIGHT_TRAIT_2_27: 'Fierce',
KNIGHT_TRAIT_2_28: 'Gifted',
KNIGHT_TRAIT_2_29: 'Glorious',
KNIGHT_TRAIT_2_30: 'Wonderful',
KNIGHT_TRAIT_2_31: 'Important',
KNIGHT_TRAIT_2_32: 'Light',
KNIGHT_TRAIT_2_33: 'Magnificent',
KNIGHT_TRAIT_2_34: 'Mysterious',
KNIGHT_TRAIT_2_35: 'Outrageous',
KNIGHT_TRAIT_2_36: 'Outstanding',
KNIGHT_TRAIT_2_37: 'Perfect',
KNIGHT_TRAIT_2_38: 'Real',
KNIGHT_TRAIT_2_39: 'Silver',
KNIGHT_TRAIT_2_40: 'Sparkling',
KNIGHT_TRAIT_2_41: 'Splendid',
KNIGHT_TRAIT_2_42: 'Successful',
KNIGHT_TRAIT_2_43: 'Super',
KNIGHT_TRAIT_2_44: 'Talented',
KNIGHT_TRAIT_2_45: 'Ugliest',
KNIGHT_TRAIT_2_46: 'Unusual',
KNIGHT_TRAIT_2_47: 'Victorious',
KNIGHT_TRAIT_2_48: 'Wandering',
KNIGHT_TRAIT_2_49: 'Wild',
KNIGHT_TRAIT_2_50: 'Zealous',
KNIGHT_TRAIT_2_51: 'Alien',
KNIGHT_TRAIT_2_52: 'Poet',
KNIGHT_TRAIT_2_53: 'Killer',
KNIGHT_TRAIT_2_54: 'Singing',
KNIGHT_TRAIT_2_55: 'Murderer',
KNIGHT_TRAIT_2_56: 'Avenger',
KNIGHT_TRAIT_2_57: 'Spy',
KNIGHT_TRAIT_2_58: 'Memorable',
KNIGHT_TRAIT_2_59: 'Exceptional',
KNIGHT_TRAIT_2_60: 'Amazing',
KNIGHT_TRAIT_2_61: 'Extreme',
KNIGHT_TRAIT_2_62: 'Ninja',
KNIGHT_TRAIT_2_63: 'Mesmerizing',
KNIGHT_TRAIT_2_64: 'Overpowered',
KNIGHT_TRAIT_2_65: 'Martian',
KNIGHT_TRAIT_2_66: 'Spartan',
KNIGHT_TRAIT_2_67: 'Streamer',
KNIGHT_TRAIT_2_68: 'Glowing',
KNIGHT_TRAIT_2_69: 'Cat',
KNIGHT_TRAIT_2_70: 'Monster',
KNIGHT_TRAIT_2_71: 'Elf',
KNIGHT_TRAIT_2_72: 'Barbarian',
KNIGHT_TRAIT_2_73: 'Dwarf',
KNIGHT_TRAIT_2_74: 'Orc',
KNIGHT_TRAIT_2_75: 'Goblin',
KNIGHT_TRAIT_2_76: 'Ghoul',
KNIGHT_TRAIT_2_77: 'Cyclops',
KNIGHT_TRAIT_2_78: 'Prettiest',
KNIGHT_TRAIT_2_79: 'Spirit',
KNIGHT_TRAIT_2_80: 'Ambidextrous',
KNIGHT_TRAIT_2_81: 'Ghost',
KNIGHT_TRAIT_2_82: 'Chicken',
KNIGHT_TRAIT_2_83: 'Elastic',
KNIGHT_TRAIT_2_84: 'Overpowering',
KNIGHT_TRAIT_2_85: 'Nerd',
KNIGHT_TRAIT_2_86: 'Brilliant',
KNIGHT_TRAIT_2_87: 'Knowledgeable',
KNIGHT_TRAIT_2_88: 'Penetrating',
KNIGHT_TRAIT_2_89: 'Indomitable',
KNIGHT_TRAIT_2_90: 'Incredible',
KNIGHT_TRAIT_2_91: 'Fluffy',
KNIGHT_TRAIT_2_92: 'Irresistible',
KNIGHT_TRAIT_2_93: 'Aerial',
KNIGHT_TRAIT_2_94: 'Daddy',
KNIGHT_TRAIT_2_95: 'Medium',
KNIGHT_TRAIT_2_96: 'Amphibian',
KNIGHT_TRAIT_2_97: 'Tainelaba',
KNIGHT_TRAIT_2_98: 'Snowman',
KNIGHT_TRAIT_2_99: 'Hippy',
KNIGHT_TRAIT_3_0: 'Immaculate',
KNIGHT_TRAIT_3_1: 'Lightning',
KNIGHT_TRAIT_3_2: 'Golden',
KNIGHT_TRAIT_3_3: 'Stormy',
KNIGHT_TRAIT_3_4: 'Monstruous',
KNIGHT_TRAIT_3_5: 'Draconic',
KNIGHT_TRAIT_3_6: 'Reincarnated',
KNIGHT_TRAIT_3_7: 'Inhuman',
KNIGHT_TRAIT_3_8: 'Mystical',
KNIGHT_TRAIT_3_9: 'Mystic',
KNIGHT_TRAIT_3_10: 'Devilish',
KNIGHT_TRAIT_3_11: 'Demonic',
KNIGHT_TRAIT_3_12: 'Demoniac',
KNIGHT_TRAIT_3_13: 'Diabolic',
KNIGHT_TRAIT_3_14: 'Diehard',
KNIGHT_TRAIT_3_15: 'Sinless',
KNIGHT_TRAIT_3_16: 'Unique',
KNIGHT_TRAIT_3_17: 'Android',
KNIGHT_TRAIT_3_18: 'Seismic',
KNIGHT_TRAIT_3_19: 'Hyper',
KNIGHT_TRAIT_3_20: 'Mega',
KNIGHT_TRAIT_3_21: 'Ultra',
KNIGHT_TRAIT_3_22: 'Giga',
KNIGHT_TRAIT_3_23: 'Proton',
KNIGHT_TRAIT_3_24: 'Clown',
KNIGHT_TRAIT_3_25: 'Vampire',
KNIGHT_TRAIT_3_26: 'Dragon',
KNIGHT_TRAIT_3_27: 'Vampiric',
KNIGHT_TRAIT_3_28: 'Best',
KNIGHT_TRAIT_3_29: 'Greatest',
KNIGHT_TRAIT_3_30: 'Robot',
KNIGHT_TRAIT_3_31: 'Cyborg',
KNIGHT_TRAIT_3_32: 'Terrific',
KNIGHT_TRAIT_3_33: 'Royal',
KNIGHT_TRAIT_3_34: 'Xmas Elf',
KNIGHT_TRAIT_3_35: 'Diver',
KNIGHT_TRAIT_4_0: 'Saint',
KNIGHT_TRAIT_4_1: 'Evil',
KNIGHT_TRAIT_4_2: 'Immortal',
KNIGHT_TRAIT_4_3: 'Homeless',
KNIGHT_TRAIT_4_4: 'Shiny',
KNIGHT_TRAIT_4_5: 'Diamond',
KNIGHT_TRAIT_4_6: 'Virgin',
KNIGHT_TRAIT_4_7: 'Astral',
KNIGHT_TRAIT_4_8: 'Hermaphrodite',
KNIGHT_TRAIT_4_9: 'Undefined',
KNIGHT_TRAIT_4_10: 'Invincible',
KNIGHT_TRAIT_4_11: 'Lvl.100',
KNIGHT_TRAIT_4_12: 'Unreal',
KNIGHT_TRAIT_4_13: 'Almighty',
KNIGHT_TRAIT_4_14: 'Divine',
KNIGHT_TRAIT_4_15: 'Satanic',
KNIGHT_TRAIT_4_16: 'Developer',
KNIGHT_TRAIT_4_17: 'Santa',
KNIGHT_TRAIT_4_18: 'Mermaid',
KNIGHT_JOB_0_0: 'Slave',
KNIGHT_JOB_0_1: 'Civilian',
KNIGHT_JOB_0_2: 'Squire',
KNIGHT_JOB_0_3: 'Stableman',
KNIGHT_JOB_0_4: 'Militaryman',
KNIGHT_JOB_0_5: 'Warmonger',
KNIGHT_JOB_0_6: 'Guard',
KNIGHT_JOB_0_7: 'Man of Arms',
KNIGHT_JOB_0_8: 'Horseman',
KNIGHT_JOB_0_9: 'Soldier',
KNIGHT_JOB_0_10: 'Novice',
KNIGHT_JOB_0_11: 'Beginner',
KNIGHT_JOB_0_12: 'Rookie',
KNIGHT_JOB_0_13: 'Pikeman',
KNIGHT_JOB_0_14: 'Bandit',
KNIGHT_JOB_0_15: 'Rogue',
KNIGHT_JOB_0_16: 'Watcher',
KNIGHT_JOB_0_17: 'Wanderer',
KNIGHT_JOB_0_18: 'Hangman',
KNIGHT_JOB_0_19: 'Bodyguard',
KNIGHT_JOB_0_20: 'Adventurer',
KNIGHT_JOB_0_21: 'Warrior',
KNIGHT_JOB_0_22: 'Fighter',
KNIGHT_JOB_0_23: 'Killer',
KNIGHT_JOB_0_24: 'Zealot',
KNIGHT_JOB_0_25: 'Disciple',
KNIGHT_JOB_0_26: 'Baker',
KNIGHT_JOB_0_27: 'Blacksmith',
KNIGHT_JOB_1_0: 'Berserker',
KNIGHT_JOB_1_1: 'Officer',
KNIGHT_JOB_1_2: 'Swordsman',
KNIGHT_JOB_1_3: 'Mercenary',
KNIGHT_JOB_1_4: 'Armored Priest',
KNIGHT_JOB_1_5: 'Guardian',
KNIGHT_JOB_1_6: 'Armored Mage',
KNIGHT_JOB_1_7: 'Cavalryman',
KNIGHT_JOB_1_8: 'Lancer',
KNIGHT_JOB_1_9: 'Fencer',
KNIGHT_JOB_1_10: 'Assassin',
KNIGHT_JOB_1_11: 'Barbarian',
KNIGHT_JOB_1_12: 'Cleric',
KNIGHT_JOB_1_13: 'Warden',
KNIGHT_JOB_1_14: 'Ardent',
KNIGHT_JOB_1_15: 'Beast',
KNIGHT_JOB_1_16: 'Drunken Fighter',
KNIGHT_JOB_1_17: 'Slayer',
KNIGHT_JOB_1_18: 'Viking',
KNIGHT_JOB_1_19: 'Centurion',
KNIGHT_JOB_1_20: 'Leader',
KNIGHT_JOB_1_21: 'Exservice',
KNIGHT_JOB_1_22: 'Knight',
KNIGHT_JOB_1_23: 'Tank',
KNIGHT_JOB_1_24: 'Samurai',
KNIGHT_JOB_1_25: 'Practitioner',
KNIGHT_JOB_1_26: 'Joker',
KNIGHT_JOB_1_27: 'Buccaneer',
KNIGHT_JOB_2_0: 'Chief',
KNIGHT_JOB_2_1: 'Captain',
KNIGHT_JOB_2_2: 'War Mage',
KNIGHT_JOB_2_3: 'Paladin',
KNIGHT_JOB_2_4: 'War Priest',
KNIGHT_JOB_2_5: 'Crusader',
KNIGHT_JOB_2_6: 'Hospitaller',
KNIGHT_JOB_2_7: 'Teutonic',
KNIGHT_JOB_2_8: 'Lord',
KNIGHT_JOB_2_9: 'Avenger',
KNIGHT_JOB_2_10: 'Swordmage',
KNIGHT_JOB_2_11: 'Psion Warrior',
KNIGHT_JOB_2_12: 'Battlemind',
KNIGHT_JOB_2_13: 'Totem Warrior',
KNIGHT_JOB_2_14: 'Battlerager',
KNIGHT_JOB_2_15: 'Herald',
KNIGHT_JOB_2_16: 'Battle Master',
KNIGHT_JOB_2_17: 'Drunken Master',
KNIGHT_JOB_2_18: 'Beast Master',
KNIGHT_JOB_2_19: 'Monster Slayer',
KNIGHT_JOB_2_20: 'Mastermind',
KNIGHT_JOB_2_21: 'Master of Arms',
KNIGHT_JOB_2_22: 'Cultivator',
KNIGHT_JOB_2_23: 'Donjon Farmer',
KNIGHT_JOB_3_0: 'General',
KNIGHT_JOB_3_1: 'Commander',
KNIGHT_JOB_3_2: 'Elite',
KNIGHT_JOB_3_3: 'Swordsmaster',
KNIGHT_JOB_3_4: 'Bandit King',
KNIGHT_JOB_3_5: 'Warlord',
KNIGHT_JOB_3_6: 'Rune Priest',
KNIGHT_JOB_3_7: 'Rune Knight',
KNIGHT_JOB_3_8: 'Swarmkeeper',
KNIGHT_JOB_3_9: 'Dragon Slayer',
KNIGHT_JOB_3_10: 'Monster Hunter',
KNIGHT_JOB_3_11: 'Daedra',
KNIGHT_JOB_3_12: 'Vigilante',
KNIGHT_JOB_3_13: 'Nascent Soul',
KNIGHT_JOB_4_0: 'God',
KNIGHT_JOB_4_1: 'Demigod',
KNIGHT_JOB_4_2: 'Saint',
KNIGHT_JOB_4_3: 'Sword Saint',
KNIGHT_JOB_4_4: 'Hero',
KNIGHT_JOB_4_5: 'Witcher',
KNIGHT_JOB_4_6: 'Dragon Hunter',
KNIGHT_JOB_4_7: 'Champion',
KNIGHT_JOB_4_8: 'Conqueror',
KNIGHT_JOB_4_9: 'King',
KNIGHT_JOB_4_10: 'Shinigami',
KNIGHT_JOB_4_11: 'Immortal',
};